=== glockyco/EqBench/src/test/resources/c-eq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "function name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "function name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ran/poidev/Eq/C-Desc.json
{
  "benchmark name": "ran",
  "program name": "poidev",
  "function name": "snippet",
  "LOC":39,
  "# Loops":3,
  "# non-linear arithmetics":13,
  "changes": 
  [
    {
      "change line": 16,
      "change type": "Insert", 
      "change operation": "Extract variable" 
    },
    {
      "change line": 18,
      "change type": "Delete", 
      "change operation": "Unused variable" 
    },
    {
      "change line": 42,
      "change type": "Update", 
      "change operation": "Replace variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/rf/Eq/C-Desc.json
{
  "benchmark name": "ell",
  "program name": "rf",
  "function name": "snippet",
  "LOC":43,
  "# Loops":1,
  "# non-linear arithmetics":25,
  "changes": 
  [
    {
      "change line": 50,
      "change type": "Insert", 
      "change operation": "Extract variable"
    },
    {
      "change line": 51,
      "change type": "Update", 
      "change operation": "Replace variable"
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessk/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessk",
  "function name": "snippet",
  "LOC":17,
  "# Loops":1,
  "# non-linear arithmetics":3,
  "changes": 
  [
    {
      "change line": 20,
      "change type": "Insert", 
      "change operation": "Split temporary variable" 
    },
    {
      "change line": 21,
      "change type": "Update", 
      "change operation": "Split temporary variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/LoopMult2/Eq/C-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "LoopMult2.main",
  "function name": "foo",
  "LOC":9,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 3,
      "change type": "Update", 
      "change operation": "Switch variable"
    },
    {
      "change line": 4,
      "change type": "Update", 
      "change operation": "Switch variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessk0/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessk0",
  "function name": "snippet",
  "LOC":13,
  "# Loops":0,
  "# non-linear arithmetics":22,
  "changes": 
  [
    {
      "change line": 8,
      "change type": "Insert", 
      "change operation": "Extract Variable" 
    },
    {
      "change line": 8,
      "change type": "Update", 
      "change operation": "Replace Variable" 
    },
    {
      "change line": 13,
      "change type": "Update", 
      "change operation": "Replace Variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessi/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessi",
  "function name": "snippet",
  "LOC":38,
  "# Loops":1,
  "# non-linear arithmetics":19,
  "changes": 
  [
    {
      "change line": 22,
      "change type": "Update", 
      "change operation": "Initial value" 
    },
    {
      "change line": 23,
      "change type": "Insert", 
      "change operation": "Dummy statement"
    },
    {
      "change line": 31,
      "change type": "Update", 
      "change operation": "Replace variable with value" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessy/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessy",
  "function name": "snippet",
  "LOC":19,
  "# Loops":1,
  "# non-linear arithmetics":3,
  "changes": 
  [
    {
      "change line": 14,
      "change type": "Insert", 
      "change operation": "Extract Variable" 
    },
    {
      "change line": 15,
      "change type": "Update", 
      "change operation": "Replace Variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ran/gasdev/Eq/C-Desc.json
{
  "benchmark name": "ran",
  "program name": "gasdev",
  "function name": "snippet",
  "LOC":25,
  "# Loops":1,
  "# non-linear arithmetics":10,
  "changes": 
  [
    {
      "change line": 9,
      "change type": "Insert", 
      "change operation": "Extract variable" 
    },
    {
      "change line": 23,
      "change type": "Delete", 
      "change operation": "Unused variable" 
    },
    {
      "change line": "25-26",
      "change type": "Insert", 
      "change operation": "Replace variable" 
    }
  ]
}
