=== glockyco/EqBench/src/test/resources/c-eq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "function name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "function name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/tcas/altseptest/Eq/C-Desc.json
{
  "benchmark name": "tcas",
  "program name": "altseptest",
  "function name": "snippet",
  "LOC":49,
  "# Loops":0,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 35,
      "change type": "Update", 
      "change operation": "Decompose Condition" 
    },
    {
      "change line": 49,
      "change type": "Update", 
      "change operation": "Decompose Condition" 
    },
    {
      "change line": "62-64",
      "change type": "Insert", 
      "change operation": "Extract Method" 
    },
    {
      "change line": "65-67",
      "change type": "Update", 
      "change operation": "Extract Method"
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessy1/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessy1",
  "function name": "snippet",
  "LOC":20,
  "# Loops":0,
  "# non-linear arithmetics":31,
  "changes": 
  [
    {
      "change line": 8,
      "change type": "Update", 
      "change operation": "Remove dead code" 
    },
    {
      "change line": 26,
      "change type": "Update", 
      "change operation": "Replace Variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/SIGN/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "SIGN",
  "function name": "snippet",
  "LOC":13,
  "# Loops":0,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 5,
      "change type": "Update", 
      "change operation": "Consolidate if conditions" 
    },
    {
      "change line": 7,
      "change type": "Update", 
      "change operation": "Consolidate if conditions" 
    },
    {
      "change line": 9,
      "change type": "Update", 
      "change operation": "Consolidate if conditions" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ran/ranzero/Eq/C-Desc.json
{
  "benchmark name": "ran",
  "program name": "ranzero",
  "function name": "snippet",
  "LOC":17,
  "# Loops":0,
  "# non-linear arithmetics":8,
  "changes": 
  [
    {
      "change line": 16,
      "change type": "Update", 
      "change operation": "Replace variable" 
    },
    {
      "change line": 20,
      "change type": "Delete", 
      "change operation": "Unused variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/sine/mysin/Eq/C-Desc.json
{
  "benchmark name": "sine",
  "program name": "mysin",
  "function name": "snippet",
  "LOC":144,
  "# Loops":0,
  "# non-linear arithmetics":47,
  "changes": 
  [
    {
      "change line": 17,
      "change type": "Update", 
      "change operation": "Rename variable" 
    },
    {
      "change line": 76,
      "change type": "Update", 
      "change operation": "Rename variable" 
    },
    {
      "change line": 138,
      "change type": "Insert", 
      "change operation": "Unreachable code" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/Comp/Eq/C-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "Comp.main",
  "function name": "foo",
  "LOC":16,
  "# Loops":0,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 2,
      "change type": "Update", 
      "change operation": "Negate the condition"
    },
    {
      "change line": 10,
      "change type": "Update", 
      "change operation": "Negate the condition"
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/plgndr/Eq/C-Desc.json
{
  "benchmark name": "ell",
  "program name": "plgndr",
  "function name": "snippet",
  "LOC":31,
  "# Loops":2,
  "# non-linear arithmetics":13,
  "changes": 
  [
    {
      "change line": 12,
      "change type": "Insert", 
      "change operation": "Extract variable"
    },
    {
      "change line": 18,
      "change type": "Update", 
      "change operation": "with Dummy value"
    },
    {
      "change line": 25,
      "change type": "Update", 
      "change operation": "Replace variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/caldat/badluk/Eq/C-Desc.json
{
  "benchmark name": "caldat",
  "program name": "badluk",
  "function name": "snippet",
  "LOC":49,
  "# Loops":3,
  "# non-linear arithmetics":4,
  "changes": 
  [
    {
      "change line": 17,
      "change type": "Insertion", 
      "change operation": "Extract variable" 
    },
    {
      "change line": 19,
      "change type": "Update", 
      "change operation": "Replace variable" 
    },
    {
      "change line": 25,
      "change type": "Update", 
      "change operation": "Replace variable" 
    }
  ]
}
