=== glockyco/EqBench/src/test/resources/c-eq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "function name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "function name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/gam/gser/Eq/C-Desc.json
{
  "benchmark name": "gam",
  "program name": "gser",
  "function name": "snippet",
  "LOC":23,
  "# Loops":1,
  "# non-linear arithmetics":7,
  "changes": 
  [
    {
      "change line": 14,
      "change type": "Insert", 
      "change operation": "Dummy statement" 
    },
    {
      "change line": 23,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 24,
      "change type": "Update", 
      "change operation": "Replace variable"  
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/REVE/triangularMod/Eq/C-Desc.json
{
  "benchmark name": "REVE",
  "program name": "triangularMod.f",
  "function name": "f",
  "LOC":20,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": "15,17",
      "change type": "Insertion", 
      "change operation": "adding a TRUE if-condition"
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/Sub/Eq/C-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "Sub.main",
  "function name": "foo",
  "LOC":12,
  "# Loops":0,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 2,
      "change type": "Update", 
      "change operation": "Switch variable"
    },
    {
      "change line": 6,
      "change type": "Update", 
      "change operation": "Switch calling parameters" 
    }
  ]
}

=== glockyco/EqBench/benchmarks/REVE/triangularMod/Neq/C-Desc.json
{
  "benchmark name": "REVE",
  "program name": "triangularMod.f",
  "function name": "f",
  "LOC":20,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": "8",
      "change type": "Insertion", 
      "change operation": "increasing the loop iterator"
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/gam/betai/Eq/C-Desc.json
{
  "benchmark name": "gam",
  "program name": "betai",
  "function name": "snippet",
  "LOC":10,
  "# Loops":0,
  "# non-linear arithmetics":10,
  "changes": 
  [
    {
      "change line": 13,
      "change type": "Update", 
      "change operation": "Decompose condition" 
    },
    {
      "change line": "18-19",
      "change type": "Insert", 
      "change operation": "Extract Method" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessk1/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessk1",
  "function name": "snippet",
  "LOC":13,
  "# Loops":0,
  "# non-linear arithmetics":22,
  "changes": 
  [
    {
      "change line": 10,
      "change type": "Update", 
      "change operation": "Replace condition" 
    },
    {
      "change line": 14,
      "change type": "Update", 
      "change operation": "Replace condition" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/dbrent/Eq/C-Desc.json
{
  "benchmark name": "ell",
  "program name": "dbrent",
  "function name": "snippet",
  "LOC":124,
  "# Loops":1,
  "# non-linear arithmetics":36,
  "changes": 
  [
    {
      "change line": 49,
      "change type": "Insert", 
      "change operation": "Extract variable" 
    },
    {
      "change line": 51,
      "change type": "Update", 
      "change operation": "Replace variable" 
    },
    {
      "change line": 53,
      "change type": "Update", 
      "change operation": "Replace variable" 
    }
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/probks/Eq/C-Desc.json
{
  "benchmark name": "bess",
  "program name": "probks",
  "function name": "snippet",
  "LOC":19,
  "# Loops":1,
  "# non-linear arithmetics":7,
  "changes": 
  [
    {
      "change line": 15,
      "change type": "Insert", 
      "change operation": "Split temporary variable" 
    },
    {
      "change line": 16,
      "change type": "Update", 
      "change operation": "Replace Variable" 
    },
    {
      "change line": 22,
      "change type": "Update", 
      "change operation": "Replace statement"  
    }
  ]
}
