=== glockyco/EqBench/src/test/resources/java-neq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "method name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" },
    "counter-example": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "method name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes",
    "counter-example"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/LoopSub/Neq/J-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "LoopSub.main",
  "method name": "foo",
  "LOC":8,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 4,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 5,
      "change type": "Update", 
      "change operation": "Comparison operand" 
    },
    {
      "change line": 5,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    }
  ],
  "counter-example":
  [
      {"int x":5}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/caldat/badluk/Neq/J-Desc.json
{
  "benchmark name": "caldat",
  "program name": "badluk",
  "method name": "snippet",
  "LOC":49,
  "# Loops":3,
  "# non-linear arithmetics":4,
  "changes": 
  [
    {
      "change line": 20,
      "change type": "Update", 
      "change operation": "Comparison operator" 
    },
    {
      "change line": 29,
      "change type": "Update", 
      "change operation": "Comparison"  
    },
    {
      "change line": 35,
      "change type": "Update", 
      "change operation": "Comparison operator" 
    }
  ],
  "counter-example":
  [
      {"int IYBEG":10}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/caldat/julday/Neq/J-Desc.json
{
  "benchmark name": "caldat",
  "program name": "julday",
  "method name": "snippet",
  "LOC":24,
  "# Loops":0,
  "# non-linear arithmetics":10,
  "changes": 
  [
    {
      "change line": 10,
      "change type": "Insert", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 25,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    }
  ],
  "counter-example":
  [
      {"double mmj":10.0},
      {"double idj":10.0},
      {"double iyyyj":0.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/pythag/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "pythag",
  "method name": "snippet",
  "LOC":17,
  "# Loops":0,
  "# non-linear arithmetics":8,
  "changes": 
  [
    {
      "change line": 8,
      "change type": "Update", 
      "change operation": "Comparison operator" 
    },
    {
      "change line": 12,
      "change type": "Update", 
      "change operation": "Comparison operand" 
    },
    {
      "change line": 15,
      "change type": "Update", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double a":20.0},
      {"double b":10.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/rf/Neq/J-Desc.json
{
  "benchmark name": "ell",
  "program name": "rf",
  "method name": "snippet",
  "LOC":43,
  "# Loops":1,
  "# non-linear arithmetics":25,
  "changes": 
  [
    {
      "change line": 26,
      "change type": "Insert", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 34,
      "change type": "Update", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 39,
      "change type": "Delete", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double x":-1.0},
      {"double y":-1.0},
      {"double z":-1.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/gam/erfcc/Neq/J-Desc.json
{
  "benchmark name": "gam",
  "program name": "erfcc",
  "method name": "snippet",
  "LOC":13,
  "# Loops":0,
  "# non-linear arithmetics":15,
  "changes": 
  [
    {
      "change line": 11,
      "change type": "Update", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 14,
      "change type": "Update", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double x":0.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessy1/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessy1",
  "method name": "snippet",
  "LOC":20,
  "# Loops":0,
  "# non-linear arithmetics":31,
  "changes":  
  [
    {
      "change line": 10,
      "change type": "Update", 
      "change operation": "Comparison operator"
    },
    {
      "change line": 22,
      "change type": "Delete", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double x":8.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/SQR/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "SQR",
  "method name": "snippet",
  "LOC":3,
  "# Loops":0,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 5,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    }
  ],
  "counter-example":
  [
      {"double a":10.0}
  ]
}
