=== glockyco/EqBench/src/test/resources/java-neq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "method name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" },
    "counter-example": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "method name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes",
    "counter-example"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessj1/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessj1",
  "method name": "snippet",
  "LOC":26,
  "# Loops":0,
  "# non-linear arithmetics":25,
  "changes": 
  [
    {
      "change line": 20,
      "change type": "Delete", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 25,
      "change type": "Insert",
      "change operation": "Logical clause" 
    }
  ],
  "counter-example":
  [
      {"double x":11.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessi1/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessi1",
  "method name": "snippet",
  "LOC":20,
  "# Loops":0,
  "# non-linear arithmetics":23,
  "changes": 
  [
    {
      "change line": 10,
      "change type": "Update", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 17,
      "change type": "Insert", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 19,
      "change type": "Insert", 
      "change operation": "Logical clause" 
    }
  ],
  "counter-example":
  [
      {"double x":20.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/probks/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "probks",
  "method name": "snippet",
  "LOC":19,
  "# Loops":1,
  "# non-linear arithmetics":7,
  "changes": 
  [
    {
      "change line": 7,
      "change type": "Delete", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 8,
      "change type": "Update", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 20,
      "change type": "Update", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double x":10.0}
  ]
}
