=== glockyco/EqBench/src/test/resources/java-neq-desc-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "benchmark name": { "$ref": "desc-properties-schema.json" },
    "program name": { "$ref": "desc-properties-schema.json" },
    "method name": { "$ref": "desc-properties-schema.json" },
    "LOC": { "$ref": "desc-properties-schema.json" },
    "# Loops": { "$ref": "desc-properties-schema.json" },
    "# non-linear arithmetics": { "$ref": "desc-properties-schema.json" },
    "changes": { "$ref": "desc-properties-schema.json" },
    "counter-example": { "$ref": "desc-properties-schema.json" }
  },
  "required": [
    "benchmark name",
    "program name",
    "method name",
    "LOC",
    "# Loops",
    "# non-linear arithmetics",
    "changes",
    "counter-example"
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ran/expdev/Neq/J-Desc.json
{
  "benchmark name": "ran",
  "program name": "expdev",
  "method name": "snippet",
  "LOC":7,
  "# Loops":1,
  "# non-linear arithmetics":1,
  "changes": 
  [
    {
      "change line": 9,
      "change type": "Insert", 
      "change operation": "Arithmetic" 
    }
  ],
  "counter-example":
  [
      {"int idumx":100.0},
      {"int idum":100.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/LoopUnreach2/Neq/J-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "LoopUnreach2.main",
  "method name": "foo",
  "LOC":9,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 4,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 6,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 7,
      "change type": "Update", 
      "change operation": "Arithmetic" 
    }
  ],
  "counter-example":
  [
      {"int x":5}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/bess/bessj0/Neq/J-Desc.json
{
  "benchmark name": "bess",
  "program name": "bessj0",
  "method name": "snippet",
  "LOC":24,
  "# Loops":0,
  "# non-linear arithmetics":25,
  "changes": 
  [
    {
      "change line": 12,
      "change type": "Update", 
      "change operation": "Comparison operand"
    },
    {
      "change line": 20,
      "change type": "Update", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double x":10.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/dbrent/Neq/J-Desc.json
{
  "benchmark name": "ell",
  "program name": "dbrent",
  "method name": "snippet",
  "LOC":124,
  "# Loops":1,
  "# non-linear arithmetics":36,
  "changes": 
  [
    {
      "change line": 83,
      "change type": "Update", 
      "change operation": "Logical operator"
    },
    {
      "change line": 89,
      "change type": "Insert", 
      "change operation": "Logical clause"
    },
    {
      "change line": 91,
      "change type": "Update", 
      "change operation": "Arithmetic"
    }
  ],
  "counter-example":
  [
      {"double ax":20.0},
      {"double bx":10.0},
      {"double cx":20.0},
      {"double tol":-1.0},
      {"double bxmin":10.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/fib2/Neq/J-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "fib2.fib",
  "method name": "lib",
  "LOC":18,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": "3-10",
      "change type": "Update", 
      "change operation": "Wrong Rewrite the method without Recursion"
    }
  ],
  "counter-example":
  [
      {"int x":4}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/CLEVER/UnchLoop/Neq/J-Desc.json
{
  "benchmark name": "CLEVER",
  "program name": "UnchLoop.main",
  "method name": "foo",
  "LOC":9,
  "# Loops":1,
  "# non-linear arithmetics":0,
  "changes": 
  [
    {
      "change line": 4,
      "change type": "Update", 
      "change operation": "Initial value"
    },
    {
      "change line": 8,
      "change type": "Update", 
      "change operation": "Return statement" 
    },
    {
      "change line": 11,
      "change type": "Update", 
      "change operation": "Calling parameter"
    }
  ],
  "counter-example":
  [
      {"int x":5}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ell/brent/Neq/J-Desc.json
{
  "benchmark name": "ell",
  "program name": "brent",
  "method name": "snippet",
  "LOC":81,
  "# Loops":1,
  "# non-linear arithmetics":28,
  "changes": 
  [
    {
      "change line": 32,
      "change type": "Update", 
      "change operation": "Arithmetic"
    },
    {
      "change line": 36,
      "change type": "Update", 
      "change operation": "Logical operator"
    },
    {
      "change line": 78,
      "change type": "Delete", 
      "change operation": "Logical clause"
    }
  ],
  "counter-example":
  [
      {"double ax":20.0},
      {"double bx":100.0},
      {"double cx":50.0},
      {"double tol":-1.0},
      {"double bxmin":10.0}
  ]
}

=== glockyco/EqBench/src/main/code/benchmarks/ran/bnldev/Neq/J-Desc.json
{
  "benchmark name": "ran",
  "program name": "bnldev",
  "method name": "snippet",
  "LOC":71,
  "# Loops":4,
  "# non-linear arithmetics":16,
  "changes": 
  [
    {
      "change line": 28,
      "change type": "Update", 
      "change operation": "Comparison operand" 
    },
    {
      "change line": 67,
      "change type": "Insert", 
      "change operation": "Arithmetic" 
    },
    {
      "change line": 69,
      "change type": "Update", 
      "change operation": "Logical clause" 
    }
  ],
  "counter-example":
  [
      {"double pp":0.006},
      {"int n":30},
      {"int idumx":-100.0},
      {"int idum":-100.0}
  ]
}
